theme: jekyll-theme-cayman
defaults:
  - scope:
      path: "/docs/en"
      type: docs
    values:
      sidebar:
        nav: "docs"
  - scope:
      path: "docs/cn"
      type: docs
    values:
      sidebar:
        nav: "docs1"